# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c4ba09b244a5a8f32d8584acce91286ebb45e79932985ff5ff3f8f822b3c0f0cfb5d5e72c1d2140f243d0fb520cb6608382ab042e28d16d6c276e654d560a3a

test:
  secret_key_base: 8c59ffae9a37a9a146f5e38d2d19807c9e6d9f2b487cc3f7013a8cd3d9d14621013c6967cb633c8eed7a44c7d4078ace2f5bd3e1f441c27b324400eda6d2e3e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
